docker build -t alpr:v1.0.0 .
docker run -it --restart unless-stopped --name alpr-instance --net host -e TZ=Europe/Istanbul -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/alpr:/tmp/alpr alpr:v1.0.0

gokalpgoren
    amd64:
        docker build -t gokalpgoren/alpr:v1.0.0-amd64 .
        docker run -it --restart unless-stopped --name alpr-instance --net host -e TZ=Europe/Istanbul -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/alpr:/tmp/alpr gokalpgoren/alpr:v1.0.0-amd64
    raspi4:
        docker build -t gokalpgoren/alpr:v1.0.0-raspi4 .
        docker run -it --restart unless-stopped --name alpr-instance --net host -e TZ=Europe/Istanbul -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/alpr:/tmp/alpr gokalpgoren/alpr:v1.0.0-raspi4